name: my_profile
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # helps to separate UI form business logic
  flutter_bloc: ^8.1.3

  # Service Locator for Dart and Flutter projects.
  get_it: ^7.6.4

  # A declarative routing package for Flutter
  go_router: ^10.1.2

  # Draw SVG files using Flutter.
  flutter_svg: ^2.0.7

  # Provides internationalization and localization facilities
  intl: ^0.18.0

  # A Flutter plugin to store data in secure storage
  flutter_secure_storage: ^9.0.0

  # Defines the annotations used by json_serializable to create code for JSON serialization and deserialization.
  json_annotation: ^4.8.1

  # A Flutter plugin for iOS and Android for picking images from the image library, and taking new pictures with the camera.
  image_picker: ^1.0.4

  # This plugin provides a cross-platform (iOS, Android) API to request permissions and check their status
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Provides Dart Build System builders for handling JSON.
  json_serializable: ^6.7.1
  build_runner: ^2.3.2

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
